### ISSUE TITLE
No easy input for strings

### ISSUE THREAD

**Issue by JayKayy** [micmonay/keybd_event#16]
There doesnt seem to be a method to easily type out a provided string such as:

"Hello World"

I believe this would require creating a map of sorts. looping through the characters and translating each rune into its corresponding keypress. This would be a very helpful tool for this library.

Great tooling though!

**Comment by micmonay** [comment]
I did not create this function because the output depends on the keyboard layout and in the world, there are many different layouts.

It is possible, but in my opinion, it is a function for another library or my library will become more complexity

**Comment by JayKayy** [comment]
Noted thank you for the explanation.
