### ISSUE TITLE
Example not working on Mac

### ISSUE THREAD

**Issue by massi-ang** [micmonay/keybd_event#20]
I have tried the code in the example on Mac, but nothing gets printed out. The same code works fine on Windows.

**Comment by micmonay** [comment]
My MacOS is old and has not a recent update, but exemple is work fine. I need more information to understand.

**Comment by micmonay** [comment]
I have found a possible fix. Please read the next threads and reply if this solution is good

- https://stackoverflow.com/questions/59146359/cgeventpost-fails-to-deliver-keyboard-events-to-another-process-under-catalina
- https://forums.developer.apple.com/thread/103992

**Comment by micmonay** [comment]
I have forced update on my MacBook 2010 at 10.15. I have same bug and I have found the solution, you must set accessibility authorization  on the parameters in MacOS.
![Example](https://user-images.githubusercontent.com/705503/80077645-11c09b00-854e-11ea-8b52-ad130b42028b.png)

**Comment by micmonay** [comment]
Is this solution right ?

**Comment by massi-ang** [comment]
I did not have time to check it has the project I was working on has been parked. I think that would be the right solution though.

**Comment by elbuki** [comment]
I know this issue is closed but I just want to confirm that the suggested solution worked for me. Thanks!
