### ISSUE TITLE
Feature Request: Additional keycodes

### ISSUE THREAD

**Issue by EmilyBjoerk** [micmonay/keybd_event#23]
For me the main use case would be to test "special" keys like VK_F21 (not a typo, see: [MSDN](https://docs.microsoft.com/en-gb/windows/win32/inputdev/virtual-key-codes) and [USB HID](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf)).

As far as I can see, these are currently not supported in:
https://github.com/micmonay/keybd_event/blob/45629dfc80f24dbd3a977eb1484de4620132d530/keybd_windows.go#L166-L180

Would it be possible to add these?

**Comment by micmonay** [comment]
Hi

On Mac OS I doesn't find the keycodes. Now, The library is compatible with Linux and Windows for keys F13 at F24.

Best regard

**Comment by EmilyBjoerk** [comment]
Thank you!
