### ISSUE TITLE
Remote SSH Connections...

### ISSUE THREAD

**Issue by DocDrydenn** [micmonay/keybd_event#27]
Code works perfectly locally, however, over a remote connection (like SSH), I get nadda. 

It's just a basic Ubuntu install. I've tried via MobaXterm, Putty, Windows CMD, etc... All give same results.

Any help would be a life-saver.

**Comment by micmonay** [comment]
Hi,

I believe it's normally because this library simulates hardware keyboard as if are put a keyboard in USB on the computer. Probably you write on the display of the computer, but no in your SSH

Best regard

**Comment by micmonay** [comment]
This response is it ok for you ?
