### ISSUE TITLE
VK_CAPSLOCK is invalid

### ISSUE THREAD

**Issue by zj360202** [micmonay/keybd_event#29]
kb.SetKeys(keybd_event.VK_CAPSLOCK)
kb.SetKeys(keybd_event.VK_A)
kb.Launching()
kb.Clear()
kb.SetKeys(keybd_event.VK_CAPSLOCK)
kb.SetKeys(keybd_event.VK_A)
kb.Launching()

output:
aa

**Comment by micmonay** [comment]
Hi

kb.SetKeys remove old selection, use AddKey instead of SetKeys or `SetKeys(keybd_event.VK_CAPSLOCK,keybd_event.VK_A)`.
But the best solutions for your example is :
```go
// Set shift to be pressed
kb.HasSHIFT(true) 
kb.SetKeys(keybd_event.VK_A) 
```
that solution is it ok for you ?

Best reguard

**Comment by zj360202** [comment]
thank you
