### ISSUE TITLE
Error while building for Linux Arch 386

### ISSUE THREAD

**Issue by Adnan-Jindani** [micmonay/keybd_event#47]
This is the command I used:
`GOOS=linux GOARCH=386 go build -o bin/app-386-linux app.go`

This is the error I get:
`# github.com/micmonay/keybd_event
../go/pkg/mod/github.com/micmonay/keybd_event@v1.1.1/keybd_event.go:20:9: undefined: initKeyBD`

**Comment by Adnan-Jindani** [comment]
@micmonay

**Comment by Vaisakhkm2625** [comment]
did you able to fix this?

**Comment by Adnan-Jindani** [comment]
Nope, I wasn't able to fix it

**Comment by Vaisakhkm2625** [comment]
> Nope, I wasn't able to fix it

then can i reopen this issue?

**Comment by Adnan-Jindani** [comment]
> then can i reopen this issue?

Yes, you can
