### ISSUE TITLE
Support for non-ASCII chars

### ISSUE THREAD

**Issue by taglme** [micmonay/keybd_event#9]
Is it possible to add some support for non-ASCII chars eg letters from French, Spanish, Cyrillic alphabets.
For Windows I've found SendInput function that could be used instead of keybd_event. Unicode char could be passed to this function to create keyboard event.
Maybe there are some analogs for MacOS and Linux?

**Comment by micmonay** [comment]
Hi

This library simulates the keyboard on the computer. For this reason it is not possible to choose the char.
I have updated the library for simplifying to use the special keys
You can use the new constants "VK_SP*" for simulating a key press on the keyboard. I have tested in a french keyboard if you use VK_2, you write 'é' or if you use VK_SP2 you write ']'

Best regard
